### ISSUE TITLE
Re-org doesn't work in heroku according to instructions!

### ISSUE THREAD

**Issue by scaleupcto** [ranman/gitshots#16]
According to the current instructions in the README, the new re-org which moves the python app to `/gitshots` does not deploy properly.

I tried adding a Procfile and deploying a subtree (see https://coderwall.com/p/ssxp5q) but even using this method the heroku logs showed the following errors:

```
2014-05-28T09:36:22.919298+00:00 heroku[api]: Enable Logplex by chris.clarke@talis.com
2014-05-28T09:36:22.919454+00:00 heroku[api]: Release v3 created by chris.clarke@talis.com
2014-05-28T09:44:05+00:00 heroku[slug-compiler]: Slug compilation started
2014-05-28T09:45:35+00:00 heroku[slug-compiler]: Slug compilation finished
2014-05-28T09:45:35.343205+00:00 heroku[api]: Release v4 created by chris.clarke@talis.com
2014-05-28T09:45:35.343118+00:00 heroku[api]: Deploy 9da31d8 by chris.clarke@talis.com
2014-05-28T09:45:35.250227+00:00 heroku[api]: Scale to web=1 by chris.clarke@talis.com
2014-05-28T09:45:39.187065+00:00 heroku[web.1]: Starting process with command `python app.py`
2014-05-28T09:45:40.650384+00:00 app[web.1]: Traceback (most recent call last):
2014-05-28T09:45:40.650411+00:00 app[web.1]:     app.config.from_object('gitshots.config')
2014-05-28T09:45:40.650440+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
2014-05-28T09:45:40.650505+00:00 app[web.1]:     obj = import_string(obj)
2014-05-28T09:45:40.650658+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/utils.py", line 417, in import_string
2014-05-28T09:45:40.650755+00:00 app[web.1]:     __import__(modname)
2014-05-28T09:45:40.650409+00:00 app[web.1]:   File "app.py", line 54, in <module>
2014-05-28T09:45:40.650807+00:00 app[web.1]: werkzeug.utils.ImportStringError: import_string() failed for 'gitshots.config'. Possible reasons are:
2014-05-28T09:45:40.650811+00:00 app[web.1]: - missing __init__.py in a package;
2014-05-28T09:45:40.650630+00:00 app[web.1]:     sys.exc_info()[2])
2014-05-28T09:45:40.650524+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/utils.py", line 424, in import_string
2014-05-28T09:45:40.650814+00:00 app[web.1]: - duplicated package or module name taking precedence in sys.path;
2014-05-28T09:45:40.650812+00:00 app[web.1]: - package or module path not included in sys.path;
2014-05-28T09:45:40.650809+00:00 app[web.1]: 
2014-05-28T09:45:40.650816+00:00 app[web.1]: - missing module, class, function or variable;
2014-05-28T09:45:40.650819+00:00 app[web.1]: Debugged import:
2014-05-28T09:45:40.650822+00:00 app[web.1]: - 'gitshots' not found.
2014-05-28T09:45:40.650823+00:00 app[web.1]: 
2014-05-28T09:45:40.650817+00:00 app[web.1]: 
2014-05-28T09:45:40.650820+00:00 app[web.1]: 
2014-05-28T09:45:40.650824+00:00 app[web.1]: Original exception:
2014-05-28T09:45:40.650826+00:00 app[web.1]: 
2014-05-28T09:45:40.650828+00:00 app[web.1]: ImportError: No module named gitshots.config
2014-05-28T09:45:42.274965+00:00 heroku[web.1]: State changed from starting to crashed
2014-05-28T09:45:42.276097+00:00 heroku[web.1]: State changed from crashed to starting
2014-05-28T09:45:42.261716+00:00 heroku[web.1]: Process exited with status 1
2014-05-28T09:45:48.498179+00:00 app[web.1]:     app.config.from_object('gitshots.config')
2014-05-28T09:45:48.498155+00:00 app[web.1]: Traceback (most recent call last):
2014-05-28T09:45:48.498241+00:00 app[web.1]:     obj = import_string(obj)
2014-05-28T09:45:48.498173+00:00 app[web.1]:   File "app.py", line 54, in <module>
2014-05-28T09:45:48.498264+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/utils.py", line 424, in import_string
2014-05-28T09:45:48.498364+00:00 app[web.1]:     sys.exc_info()[2])
2014-05-28T09:45:48.498181+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
2014-05-28T09:45:48.498384+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/utils.py", line 417, in import_string
2014-05-28T09:45:48.498468+00:00 app[web.1]:     __import__(modname)
2014-05-28T09:45:48.498514+00:00 app[web.1]: werkzeug.utils.ImportStringError: import_string() failed for 'gitshots.config'. Possible reasons are:
2014-05-28T09:45:48.498516+00:00 app[web.1]: 
2014-05-28T09:45:48.498521+00:00 app[web.1]: - duplicated package or module name taking precedence in sys.path;
2014-05-28T09:45:48.498518+00:00 app[web.1]: - missing __init__.py in a package;
2014-05-28T09:45:48.498523+00:00 app[web.1]: - missing module, class, function or variable;
2014-05-28T09:45:48.498519+00:00 app[web.1]: - package or module path not included in sys.path;
2014-05-28T09:45:48.498524+00:00 app[web.1]: 
2014-05-28T09:45:48.498525+00:00 app[web.1]: Debugged import:
2014-05-28T09:45:48.498527+00:00 app[web.1]: 
2014-05-28T09:45:48.498528+00:00 app[web.1]: - 'gitshots' not found.
2014-05-28T09:45:48.498530+00:00 app[web.1]: 
2014-05-28T09:45:48.498531+00:00 app[web.1]: Original exception:
2014-05-28T09:45:48.498535+00:00 app[web.1]: ImportError: No module named gitshots.config
2014-05-28T09:45:48.498532+00:00 app[web.1]: 
2014-05-28T09:45:49.968793+00:00 heroku[web.1]: State changed from starting to crashed
2014-05-28T09:45:49.955861+00:00 heroku[web.1]: Process exited with status 1
2014-05-28T09:45:46.765657+00:00 heroku[web.1]: Starting process with command `python app.py`
```

In the end I reverted the last 4 commits to https://github.com/ranman/gitshots/commit/f36e7b34790415b48f4ee67badaec8e8891b2853 to get a working setup in heroku.

**Comment by caseyjkey** [comment]
Is this issue fixed?
